export const TOOLS = [
  // ── ORGANIZE PDF ──────────────────────────────────────────────────
  {
    id: "merge-pdf",
    name: "Merge PDF",
    desc: "Gabungkan beberapa PDF menjadi satu file.",
    icon: "🔗",
    category: "organize",
    route: "/merge-pdf",
    accept: { "application/pdf": [".pdf"] },
    multiple: true,
    clientSide: true,
  },
  {
    id: "split-pdf",
    name: "Split PDF",
    desc: "Pisahkan halaman PDF menjadi beberapa file.",
    icon: "✂️",
    category: "organize",
    route: "/split-pdf",
    accept: { "application/pdf": [".pdf"] },
    multiple: false,
    clientSide: true,
  },
  {
    id: "organize-pdf",
    name: "Organize PDF",
    desc: "Urutkan, hapus, atau putar halaman PDF.",
    icon: "📋",
    category: "organize",
    route: "/organize-pdf",
    accept: { "application/pdf": [".pdf"] },
    multiple: false,
    clientSide: true,
  },
  {
    id: "rotate-pdf",
    name: "Rotate PDF",
    desc: "Putar halaman PDF ke segala arah.",
    icon: "🔄",
    category: "organize",
    route: "/rotate-pdf",
    accept: { "application/pdf": [".pdf"] },
    multiple: false,
    clientSide: true,
  },

  // ── OPTIMIZE PDF ──────────────────────────────────────────────────
  {
    id: "compress-pdf",
    name: "Compress PDF",
    desc: "Kurangi ukuran file PDF tanpa kehilangan kualitas.",
    icon: "🗜️",
    category: "optimize",
    route: "/compress-pdf",
    accept: { "application/pdf": [".pdf"] },
    multiple: false,
    clientSide: false,
  },
  {
    id: "repair-pdf",
    name: "Repair PDF",
    desc: "Perbaiki file PDF yang rusak atau corrupt.",
    icon: "🔧",
    category: "optimize",
    route: "/repair-pdf",
    accept: { "application/pdf": [".pdf"] },
    multiple: false,
    clientSide: false,
  },
  {
    id: "ocr-pdf",
    name: "OCR PDF",
    desc: "Buat PDF yang dapat dicari teksnya dengan OCR.",
    icon: "🔍",
    category: "optimize",
    route: "/ocr-pdf",
    accept: { "application/pdf": [".pdf"], "image/*": [".jpg", ".jpeg", ".png"] },
    multiple: false,
    clientSide: false,
  },

  // ── CONVERT PDF ───────────────────────────────────────────────────
  {
    id: "pdf-to-word",
    name: "PDF to Word",
    desc: "Ubah PDF menjadi dokumen Word yang dapat diedit.",
    icon: "📝",
    category: "convert",
    route: "/pdf-to-word",
    accept: { "application/pdf": [".pdf"] },
    multiple: false,
    clientSide: false,
  },
  {
    id: "pdf-to-powerpoint",
    name: "PDF to PowerPoint",
    desc: "Ubah PDF menjadi presentasi PowerPoint.",
    icon: "📊",
    category: "convert",
    route: "/pdf-to-powerpoint",
    accept: { "application/pdf": [".pdf"] },
    multiple: false,
    clientSide: false,
  },

  {
    id: "word-to-pdf",
    name: "Word to PDF",
    desc: "Ubah dokumen Word menjadi PDF.",
    icon: "📄",
    category: "convert",
    route: "/word-to-pdf",
    accept: { "application/msword": [".doc"], "application/vnd.openxmlformats-officedocument.wordprocessingml.document": [".docx"] },
    multiple: false,
    clientSide: false,
  },
  {
    id: "powerpoint-to-pdf",
    name: "PowerPoint to PDF",
    desc: "Ubah presentasi PowerPoint menjadi PDF.",
    icon: "📉",
    category: "convert",
    route: "/powerpoint-to-pdf",
    accept: { "application/vnd.ms-powerpoint": [".ppt"], "application/vnd.openxmlformats-officedocument.presentationml.presentation": [".pptx"] },
    multiple: false,
    clientSide: false,
  },
  {
    id: "excel-to-pdf",
    name: "Excel to PDF",
    desc: "Ubah spreadsheet Excel menjadi PDF.",
    icon: "🗃️",
    category: "convert",
    route: "/excel-to-pdf",
    accept: { "application/vnd.ms-excel": [".xls"], "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": [".xlsx"] },
    multiple: false,
    clientSide: false,
  },
  {
    id: "pdf-to-jpg",
    name: "PDF to JPG",
    desc: "Ubah setiap halaman PDF menjadi gambar JPG.",
    icon: "🖼️",
    category: "convert",
    route: "/pdf-to-jpg",
    accept: { "application/pdf": [".pdf"] },
    multiple: false,
    clientSide: false,
  },
  {
    id: "jpg-to-pdf",
    name: "JPG to PDF",
    desc: "Ubah gambar JPG, PNG, atau WEBP menjadi PDF.",
    icon: "🖼️",
    category: "convert",
    route: "/jpg-to-pdf",
    accept: { "image/*": [".jpg", ".jpeg", ".png", ".webp"] },
    multiple: true,
    clientSide: true,
  },
  {
    id: "html-to-pdf",
    name: "HTML to PDF",
    desc: "Ubah halaman web atau URL menjadi PDF.",
    icon: "🌐",
    category: "convert",
    route: "/html-to-pdf",
    accept: null,
    multiple: false,
    clientSide: false,
  },
  {
    id: "pdf-to-pdfa",
    name: "PDF to PDF/A",
    desc: "Ubah PDF menjadi format arsip PDF/A.",
    icon: "🗄️",
    category: "convert",
    route: "/pdf-to-pdfa",
    accept: { "application/pdf": [".pdf"] },
    multiple: false,
    clientSide: false,
  },

  // ── EDIT PDF ──────────────────────────────────────────────────────
  {
    id: "edit-pdf",
    name: "Edit PDF",
    desc: "Tambah teks, gambar, dan anotasi ke PDF.",
    icon: "✏️",
    category: "edit",
    route: "/edit-pdf",
    accept: { "application/pdf": [".pdf"] },
    multiple: false,
    clientSide: true,
  },
  {
    id: "sign-pdf",
    name: "Sign PDF",
    desc: "Tambahkan tanda tangan digital ke PDF.",
    icon: "✍️",
    category: "edit",
    route: "/sign-pdf",
    accept: { "application/pdf": [".pdf"] },
    multiple: false,
    clientSide: true,
  },
  {
    id: "watermark-pdf",
    name: "Watermark PDF",
    desc: "Tambahkan watermark teks atau gambar ke PDF.",
    icon: "💧",
    category: "edit",
    route: "/watermark-pdf",
    accept: { "application/pdf": [".pdf"] },
    multiple: false,
    clientSide: true,
  },
  {
    id: "page-numbers",
    name: "Page Numbers",
    desc: "Tambahkan nomor halaman ke PDF.",
    icon: "🔢",
    category: "edit",
    route: "/page-numbers",
    accept: { "application/pdf": [".pdf"] },
    multiple: false,
    clientSide: true,
  },
  {
    id: "crop-pdf",
    name: "Crop PDF",
    desc: "Potong area halaman PDF sesuai kebutuhan.",
    icon: "✂️",
    category: "edit",
    route: "/crop-pdf",
    accept: { "application/pdf": [".pdf"] },
    multiple: false,
    clientSide: true,
  },
  {
    id: "redact-pdf",
    name: "Redact PDF",
    desc: "Hitamkan area sensitif di PDF secara permanen.",
    icon: "⬛",
    category: "edit",
    route: "/redact-pdf",
    accept: { "application/pdf": [".pdf"] },
    multiple: false,
    clientSide: true,
  },
  {
    id: "pdf-forms",
    name: "PDF Forms",
    desc: "Buat dan isi formulir interaktif di PDF.",
    icon: "📋",
    category: "edit",
    route: "/pdf-forms",
    accept: { "application/pdf": [".pdf"] },
    multiple: false,
    clientSide: true,
  },

  {
    id: "compare-pdf",
    name: "Compare PDF",
    desc: "Bandingkan dua PDF dan lihat perbedaannya.",
    icon: "🔀",
    category: "edit",
    route: "/compare-pdf",
    accept: { "application/pdf": [".pdf"] },
    multiple: true,
    clientSide: false,
  },

  // ── PDF SECURITY ──────────────────────────────────────────────────
  {
    id: "protect-pdf",
    name: "Protect PDF",
    desc: "Tambahkan password dan enkripsi ke PDF.",
    icon: "🔒",
    category: "security",
    route: "/protect-pdf",
    accept: { "application/pdf": [".pdf"] },
    multiple: false,
    clientSide: false,
  },
  {
    id: "unlock-pdf",
    name: "Unlock PDF",
    desc: "Hapus password dan enkripsi dari PDF.",
    icon: "🔓",
    category: "security",
    route: "/unlock-pdf",
    accept: { "application/pdf": [".pdf"] },
    multiple: false,
    clientSide: false,
  },

  // ── IMAGE TOOLS ───────────────────────────────────────────────────
  {
    id: "remove-background",
    name: "Remove Background",
    desc: "Hapus background gambar dan export PNG transparan.",
    icon: "🪄",
    category: "image",
    route: "/remove-background",
    accept: { "image/jpeg": [".jpg", ".jpeg"], "image/png": [".png"] },
    multiple: false,
    clientSide: false,
  },
];

export const CATEGORIES = [
  { id: "all", label: "Semua" },
  { id: "organize", label: "Organize PDF" },
  { id: "optimize", label: "Optimize PDF" },
  { id: "convert", label: "Convert PDF" },
  { id: "edit", label: "Edit PDF" },
  { id: "security", label: "PDF Security" },
  { id: "image", label: "Image Tools" },
];
